# Generated by Django 4.1.1 on 2022-09-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='number',
            new_name='mobile',
        ),
    ]
